#ifndef _DEVICE_FEATURES_FC7300F4MDDxxxxxT1B_COMMON_H_
#define _DEVICE_FEATURES_FC7300F4MDDxxxxxT1B_COMMON_H_

#include "../FC7300_feature.h"

#include "modules/acc_feature.h"
#include "modules/adc_feature.h"
#include "modules/aontimer_feature.h"
#include "modules/cmp_feature.h"
#include "modules/cmu_feature.h"
#include "modules/cordic_feature.h"
#include "modules/core_feature.h"
#include "modules/cpm_feature.h"
#include "modules/crc_feature.h"
#include "modules/csc0_feature.h"
#include "modules/csc1_feature.h"
#include "modules/csc2_feature.h"
#include "modules/dmamux_feature.h"
#include "modules/dma_feature.h"
#include "modules/eim_feature.h"
#include "modules/enet_feature.h"
#include "modules/erm_feature.h"
#include "modules/fciic_feature.h"
#include "modules/fcpit_feature.h"
#include "modules/fcsmu_feature.h"
#include "modules/fcspi_feature.h"
#include "modules/fcuart_feature.h"
#include "modules/flash_feature.h"
#include "modules/flexcan_feature.h"
#include "modules/fmc_feature.h"
#include "modules/freqm_feature.h"
#include "modules/ftu_feature.h"
#include "modules/gpio_feature.h"
#include "modules/hsmmailbox_feature.h"
#include "modules/hsm_feature.h"
#include "modules/intm_feature.h"
#include "modules/ism_feature.h"
#include "modules/lu_feature.h"
#include "modules/mb_feature.h"
#include "modules/mam_feature.h"
#include "modules/mb_feature.h"
#include "modules/msc_feature.h"
#include "modules/ospi_feature.h"
#include "modules/pcc_feature.h"
#include "modules/pmc_feature.h"
#include "modules/port_feature.h"
#include "modules/ptimer_feature.h"
#include "modules/rgm_feature.h"
#include "modules/rtc_feature.h"
#include "modules/scg_feature.h"
#include "modules/scm_feature.h"
#include "modules/scst_feature.h"
#include "modules/sddf_feature.h"
#include "modules/sec_feature.h"
#include "modules/sent_feature.h"
#include "modules/smc_feature.h"
#include "modules/stcu_feature.h"
#include "modules/tmu_feature.h"
#include "modules/trgsel_feature.h"
#include "modules/tstmp_feature.h"
#include "modules/wdog_feature.h"
#include "modules/wku_feature.h"

#define SDADC_INSTANCE_COUNT (0u)

#endif /* _DEVICE_FEATURES_FC7300F4MDDxxxxxT1B_COMMON_H_ */
