#ifndef _DEVICE_FEATURES_FC7300F4MDSxxxxxT1C_DMAMUX_COMMON_H_
#define _DEVICE_FEATURES_FC7300F4MDSxxxxxT1C_DMAMUX_COMMON_H_

/************ DMAMUX Features **************/
/** Number of instances of the DMAMUX module. */
#define DMAMUX_INSTANCE_COUNT                    (1u)

/** Array initializer of DMAMUX peripheral base addresses */
#define DMAMUX_BASE_ADDRS                        {DMAMUX0_BASE}
/** Array initializer of DMAMUX peripheral base pointers */
#define DMAMUX_BASE_PTRS                         {DMAMUX0}

/**
 * @brief Structure for the DMA hardware request
 *
 * Defines the structure for the DMA hardware request collections. The user can configure the
 * hardware request into DMAMUX to trigger the DMA transfer accordingly. The index
 * of the hardware request varies according  to the to SoC.
 * Note that some enum members may not existed in chips, please refer to Reference Manual.
 */
typedef enum
{
    DMA_REQ_DISABLED                        = 0U,
    DMA_REQ_FCIIC0_RX                       = 1U,
    DMA_REQ_FCIIC0_TX                       = 2U,
    DMA_REQ_FCIIC1_RX                       = 3U,
    DMA_REQ_FCIIC1_TX                       = 4U,
    DMA_REQ_FCSPI0_RX                       = 5U,
    DMA_REQ_FCSPI0_TX                       = 6U,
    DMA_REQ_FCSPI1_RX                       = 7U,
    DMA_REQ_FCSPI1_TX                       = 8U,
    DMA_REQ_FCSPI2_RX                       = 9U,
    DMA_REQ_FCSPI2_TX                       = 10U,
    DMA_REQ_FCSPI3_RX                       = 11U,
    DMA_REQ_FCSPI3_TX                       = 12U,
    DMA_REQ_FCSPI4_RX                       = 13U,
    DMA_REQ_FCSPI4_TX                       = 14U,
    DMA_REQ_FCSPI5_RX                       = 15U,
    DMA_REQ_FCSPI5_TX                       = 16U,
    DMA_REQ_FTU0_CH0_OR_CRM0_CH0            = 17U,
    DMA_REQ_FTU0_CH2_OR_CRM0_CH1            = 18U,
    DMA_REQ_FTU0_CH4_OR_CRM0_CH2            = 19U,
    DMA_REQ_FTU0_CH6_OR_CRM0_CH3            = 20U,
    DMA_REQ_eFTU0_SRC8_OR_CRM0_CH4          = 21U,
    DMA_REQ_eFTU0_SRC9_OR_CRM0_CH5          = 22U,
    DMA_REQ_FLEXCAN0                        = 23U,
    DMA_REQ_FLEXCAN1                        = 24U,
    DMA_REQ_FLEXCAN2                        = 25U,
    DMA_REQ_FLEXCAN3                        = 26U,
    DMA_REQ_FLEXCAN4                        = 27U,
    DMA_REQ_FLEXCAN5                        = 28U,
    DMA_REQ_CRM0_CH6                        = 31U,
    DMA_REQ_CRM0_CH7                        = 32U,
    DMA_REQ_ADC0                            = 33U,
    DMA_REQ_ADC1                            = 34U,
    DMA_REQ_ADC2                            = 35U,
    DMA_REQ_eFTU0_SRC10                     = 39U,
    DMA_REQ_eFTU0_SRC11                     = 40U,
    DMA_REQ_FCUART0_RX                      = 41U,
    DMA_REQ_FCUART0_TX                      = 42U,
    DMA_REQ_FCUART1_RX                      = 43U,
    DMA_REQ_FCUART1_TX                      = 44U,
    DMA_REQ_FCUART2_RX                      = 45U,
    DMA_REQ_FCUART2_TX                      = 46U,
    DMA_REQ_FCUART3_RX                      = 47U,
    DMA_REQ_FCUART3_TX                      = 48U,
    DMA_REQ_FCUART4_RX                      = 49U,
    DMA_REQ_FCUART4_TX                      = 50U,
    DMA_REQ_FCUART5_RX                      = 51U,
    DMA_REQ_FCUART5_TX                      = 52U,
    DMA_REQ_FCUART6_RX                      = 53U,
    DMA_REQ_FCUART6_TX                      = 54U,
    DMA_REQ_FCUART7_RX                      = 55U,
    DMA_REQ_FCUART7_TX                      = 56U,
    DMA_REQ_FTU3_CH0                        = 57U,
    DMA_REQ_FTU3_CH2                        = 58U,
    DMA_REQ_FTU3_CH4                        = 59U,
    DMA_REQ_FTU3_CH6                        = 60U,
    DMA_REQ_Flash_ADDR                      = 61U,
    DMA_REQ_Flash_DATA                      = 62U,
    DMA_REQ_LU0                             = 63U,
    DMA_REQ_LU1                             = 64U,
    DMA_REQ_eFTU0_SRC12_OR_CRM0_CH8         = 65U,
    DMA_REQ_eFTU0_SRC13_OR_CRM0_CH9         = 66U,
    DMA_REQ_eFTU0_SRC14_OR_CRM0_CH10        = 67U,
    DMA_REQ_eFTU0_SRC0                      = 68U,
    DMA_REQ_eFTU0_SRC1                      = 69U,
    DMA_REQ_eFTU0_SRC2                      = 70U,
    DMA_REQ_eFTU0_SRC3                      = 71U,
    DMA_REQ_eFTU0_SRC4                      = 72U,
    DMA_REQ_eFTU0_SRC5                      = 73U,
    DMA_REQ_eFTU0_SRC6                      = 74U,
    DMA_REQ_eFTU0_SRC7                      = 75U,
    DMA_REQ_CRM0_CH11                       = 76U,
    DMA_REQ_PORTA                           = 77U,
    DMA_REQ_PORTB                           = 78U,
    DMA_REQ_PORTC                           = 79U,
    DMA_REQ_PORTD                           = 80U,
    DMA_REQ_PORTE                           = 81U,
    DMA_REQ_PORTF                           = 82U,
    DMA_REQ_PORTG                           = 83U,
    DMA_REQ_PORTH                           = 84U,
    DMA_REQ_PORTI                           = 85U,
    DMA_REQ_AONTIMER0                       = 86U,
    DMA_REQ_eFTU0_SRC15_OR_CRM0_CH12        = 88U,
    DMA_REQ_ADC3                            = 89U,
    DMA_REQ_PTIMER0                         = 90U,
    DMA_REQ_PTIMER1                         = 91U,
    DMA_REQ_PTIMER2                         = 92U,
    DMA_REQ_FTU0                            = 98U,
    DMA_REQ_FTU1                            = 99U,
    DMA_REQ_FTU2                            = 100U,
    DMA_REQ_FTU3                            = 101U,
    DMA_REQ_FTU4                            = 102U,
    DMA_REQ_FTU5                            = 103U,
    DMA_REQ_FTU4_CH0                        = 106U,
    DMA_REQ_FTU4_CH2                        = 107U,
    DMA_REQ_FTU4_CH4                        = 108U,
    DMA_REQ_FTU4_CH6                        = 109U,
    DMA_REQ_SENT0_FAST_CH0                  = 110U,
    DMA_REQ_SENT0_FAST_CH1                  = 111U,
    DMA_REQ_SENT0_FAST_CH2                  = 112U,
    DMA_REQ_SENT0_FAST_CH3                  = 113U,
    DMA_REQ_SENT1_FAST_CH0                  = 114U,
    DMA_REQ_SENT1_FAST_CH1                  = 115U,
    DMA_REQ_SENT1_FAST_CH2                  = 116U,
    DMA_REQ_SENT1_FAST_CH3                  = 117U,
    DMA_REQ_SENT0_SLOW_CH0                  = 118U,
    DMA_REQ_SENT0_SLOW_CH1                  = 119U,
    DMA_REQ_SENT0_SLOW_CH2                  = 120U,
    DMA_REQ_SENT0_SLOW_CH3                  = 121U,
    DMA_REQ_SENT1_SLOW_CH0                  = 122U,
    DMA_REQ_SENT1_SLOW_CH1                  = 123U,
    DMA_REQ_SENT1_SLOW_CH2                  = 124U,
    DMA_REQ_SENT1_SLOW_CH3                  = 125U,
    DMA_REQ_ALWAYS_ENABLED_0                = 126U,
    DMA_REQ_ALWAYS_ENABLED_1                = 127U
} DMA_RequestSourceType;

#endif /* _DEVICE_FEATURES_FC7300F4MDSxxxxxT1C_DMAMUX_COMMON_H_ */
