#ifndef _DEVICE_FEATURES_FC7300F8MDTxxxxxT1B_SCM_COMMON_H_
#define _DEVICE_FEATURES_FC7300F8MDTxxxxxT1B_SCM_COMMON_H_


#define SCM_GET_DEVICEID_SUPPORT              (1u)
#define SCM_GTBC_TPU_SELECT_SUPPORT           (0u)
#define SCM_GTBC_FTU_SELECT_SUPPORT           (0u)
#define SCM_FTU_GTBC_TSTMP_TRIG_SUPPORT       (0u)
#define SCM_PTIMER_CHANNEL_SELECTION_SUPPORT  (0u)
#define SCM_CRC_SUPPORT                       (1u)
#define SCM_TPUPCC_SUPPORT                    (0u)
#define SCM_FLEXHSM_PCC_SUPPORT               (0U)
#define SCM_ADC_TRIGGER_SEL_SUPPORT           (0U)
#define SCM_ADC_PRE_TRIGGER_SEL_SUPPORT       (0U)
#define SCM_HSADC_BIAS_FORCE_ENABLE_SUPPORT   (0U)

#endif /* _DEVICE_FEATURES_FC7300F8MDTxxxxxT1B_SCM_COMMON_H_ */
