#ifndef _DEVICE_FEATURES_FC7300_DMAMUX_COMMON_H_
#define _DEVICE_FEATURES_FC7300_DMAMUX_COMMON_H_

/** DMAMUX - Register Layout Typedef */
#define DMA_PERIOD_CHANNEL_COUNT                 4U

#endif /* _DEVICE_FEATURES_FC7300_DMAMUX_COMMON_H_ */
