#ifndef _DEVICE_FEATURES_FC7300_HSMMAILBOX_COMMON_H_
#define _DEVICE_FEATURES_FC7300_HSMMAILBOX_COMMON_H_

/************ HSMMAILBOX Features **************/


#endif /* _DEVICE_FEATURES_FC7300_HSMMAILBOX_COMMON_H_ */
