#ifndef _MODULE_AHB_OVERLAY_gmbhdijq41_REGS_H_AHB_OVERLAY_H_
#define _MODULE_AHB_OVERLAY_gmbhdijq41_REGS_H_AHB_OVERLAY_H_

/* ----------------------------------------------------------------------------
   -- AHB_OVERLAY Peripheral Access Layer
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup AHB_OVERLAY_Peripheral_Access_Layer AHB_OVERLAY Peripheral Access Layer
 * @{
 */

/** AHB_OVERLAY - Size of Registers Arrays */

/** AHB_OVERLAY - Register Layout Typedef */

typedef struct {

  __IO uint32_t REGION_0_SRC                  ; /* Region 0 Source Address Register, offset: 0x00 */
  __IO uint32_t REGION_0_DST                  ; /* Region 0 Destination Address Register, offset: 0x04 */
  __IO uint32_t REGION_0_SIZE                 ; /* Region 0 Size Register, offset: 0x08 */
  __IO uint32_t REGION_0_EN                   ; /* Region 0 Enable Register, offset: 0x0C */
  __IO uint32_t REGION_1_SRC                  ; /* Region 1 Source Address Register, offset: 0x10 */
  __IO uint32_t REGION_1_DST                  ; /* Region 1 Destination Address Register, offset: 0x14 */
  __IO uint32_t REGION_1_SIZE                 ; /* Region 1 Size Register, offset: 0x18 */
  __IO uint32_t REGION_1_EN                   ; /* Region 1 Enable Register, offset: 0x1C */
  __IO uint32_t REGION_2_SRC                  ; /* Region 2 Source Address Register, offset: 0x20 */
  __IO uint32_t REGION_2_DST                  ; /* Region 2 Destination Address Register, offset: 0x24 */
  __IO uint32_t REGION_2_SIZE                 ; /* Region 2 Size Register, offset: 0x28 */
  __IO uint32_t REGION_2_EN                   ; /* Region 2 Enable Register, offset: 0x2C */
       uint8_t  RESERVED_0[80];
  __IO uint32_t GLOBAL_EN                     ; /* FAR and Overlay Enable Register, offset: 0x80 */
  __I  uint32_t INTR_FLAG                     ; /* Interrupt Flag Register, offset: 0x84 */
  __O  uint32_t INTR_CLR                      ; /* Interrupt Clear Register, offset: 0x88 */
  __IO uint32_t INTR_EN                       ; /* Interrupt Enable Register, offset: 0x8C */
  __I  uint32_t FAR_SRC                       ; /* FAR Source Register, offset: 0x90 */
  __IO uint32_t FAR_DST                       ; /* FAR Destination Register, offset: 0x94 */
  __IO uint32_t FAR_SIZE                      ; /* FAR Size Register, offset: 0x98 */
       uint8_t  RESERVED_1[4];
  __I  uint32_t REGION0_MASK                  ; /* Region 0 Mask Register, offset: 0xA0 */
  __I  uint32_t REGION1_MASK                  ; /* Region 1 Mask Register, offset: 0xA4 */
  __I  uint32_t REGION2_MASK                  ; /* Region 2 Mask Register, offset: 0xA8 */

} AHB_OVERLAY_Type, *AHB_OVERLAY_MemMapPtr;


/* AHB_OVERLAY - Peripheral instance base addresses */
/** Peripheral AHB_OVERLAY base address */
#define AHB_OVERLAY_BASE                         (0xE0081000u)
/** Peripheral AHB_OVERLAY base pointer */
#define AHB_OVERLAY                              ((AHB_OVERLAY_Type *)AHB_OVERLAY_BASE)
// need fill by yourself
///** Number of interrupt vector arrays for the AHB_OVERLAY module. */
//#define AHB_OVERLAY_IRQS_ARR_COUNT                       (1u)
///** Number of interrupt channels for the AHB_OVERLAY module. */
//#define AHB_OVERLAY_IRQS_CH_COUNT                        (1u)
///** Interrupt vectors for the AHB_OVERLAY peripheral type */
//#define AHB_OVERLAY_IRQS                         {AHB_OVERLAY_IRQn}


/* ----------------------------------------------------------------------------
   -- AHB_OVERLAY Register Masks
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup AHB_OVERLAY_Register_Masks AHB_OVERLAY Register Masks
 * @{
 */

/* REGION_0_SRC Bit Fields */
#define AHB_OVERLAY_REGION_0_SRC_REGION0_SRC_MASK 0xFFFFF000u
#define AHB_OVERLAY_REGION_0_SRC_REGION0_SRC_SHIFT 12u
#define AHB_OVERLAY_REGION_0_SRC_REGION0_SRC_WIDTH 20u
#define AHB_OVERLAY_REGION_0_SRC_REGION0_SRC(x) ((uint32_t)(x) & AHB_OVERLAY_REGION_0_SRC_REGION0_SRC_MASK)
/* REGION_0_SRC Reg Mask */
#define AHB_OVERLAY_REGION_0_SRC_MASK  0xFFFFF000u

/* REGION_0_DST Bit Fields */
#define AHB_OVERLAY_REGION_0_DST_REGION0_DST_MASK 0xFFFFF000u
#define AHB_OVERLAY_REGION_0_DST_REGION0_DST_SHIFT 12u
#define AHB_OVERLAY_REGION_0_DST_REGION0_DST_WIDTH 20u
#define AHB_OVERLAY_REGION_0_DST_REGION0_DST(x) ((uint32_t)(x) & AHB_OVERLAY_REGION_0_DST_REGION0_DST_MASK)
/* REGION_0_DST Reg Mask */
#define AHB_OVERLAY_REGION_0_DST_MASK  0xFFFFF000u

/* REGION_0_SIZE Bit Fields */
#define AHB_OVERLAY_REGION_0_SIZE_REGION0_SIZE_MASK 0x1FFu
#define AHB_OVERLAY_REGION_0_SIZE_REGION0_SIZE_SHIFT 0u
#define AHB_OVERLAY_REGION_0_SIZE_REGION0_SIZE_WIDTH 9u
#define AHB_OVERLAY_REGION_0_SIZE_REGION0_SIZE(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_REGION_0_SIZE_REGION0_SIZE_SHIFT))&AHB_OVERLAY_REGION_0_SIZE_REGION0_SIZE_MASK)
/* REGION_0_SIZE Reg Mask */
#define AHB_OVERLAY_REGION_0_SIZE_MASK 0x000001FFu

/* REGION_0_EN Bit Fields */
#define AHB_OVERLAY_REGION_0_EN_REGION0_EN_MASK 0x1u
#define AHB_OVERLAY_REGION_0_EN_REGION0_EN_SHIFT 0u
#define AHB_OVERLAY_REGION_0_EN_REGION0_EN_WIDTH 1u
#define AHB_OVERLAY_REGION_0_EN_REGION0_EN(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_REGION_0_EN_REGION0_EN_SHIFT))&AHB_OVERLAY_REGION_0_EN_REGION0_EN_MASK)
/* REGION_0_EN Reg Mask */
#define AHB_OVERLAY_REGION_0_EN_MASK   0x00000001u

/* REGION_1_SRC Bit Fields */
#define AHB_OVERLAY_REGION_1_SRC_REGION1_SRC_MASK 0xFFFFF000u
#define AHB_OVERLAY_REGION_1_SRC_REGION1_SRC_SHIFT 12u
#define AHB_OVERLAY_REGION_1_SRC_REGION1_SRC_WIDTH 20u
#define AHB_OVERLAY_REGION_1_SRC_REGION1_SRC(x) ((uint32_t)(x) & AHB_OVERLAY_REGION_1_SRC_REGION1_SRC_MASK)
/* REGION_1_SRC Reg Mask */
#define AHB_OVERLAY_REGION_1_SRC_MASK  0xFFFFF000u

/* REGION_1_DST Bit Fields */
#define AHB_OVERLAY_REGION_1_DST_REGION1_DST_MASK 0xFFFFF000u
#define AHB_OVERLAY_REGION_1_DST_REGION1_DST_SHIFT 12u
#define AHB_OVERLAY_REGION_1_DST_REGION1_DST_WIDTH 20u
#define AHB_OVERLAY_REGION_1_DST_REGION1_DST(x) ((uint32_t)(x) & AHB_OVERLAY_REGION_1_DST_REGION1_DST_MASK)
/* REGION_1_DST Reg Mask */
#define AHB_OVERLAY_REGION_1_DST_MASK  0xFFFFF000u

/* REGION_1_SIZE Bit Fields */
#define AHB_OVERLAY_REGION_1_SIZE_REGION1_SIZE_MASK 0x1FFu
#define AHB_OVERLAY_REGION_1_SIZE_REGION1_SIZE_SHIFT 0u
#define AHB_OVERLAY_REGION_1_SIZE_REGION1_SIZE_WIDTH 9u
#define AHB_OVERLAY_REGION_1_SIZE_REGION1_SIZE(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_REGION_1_SIZE_REGION1_SIZE_SHIFT))&AHB_OVERLAY_REGION_1_SIZE_REGION1_SIZE_MASK)
/* REGION_1_SIZE Reg Mask */
#define AHB_OVERLAY_REGION_1_SIZE_MASK 0x000001FFu

/* REGION_1_EN Bit Fields */
#define AHB_OVERLAY_REGION_1_EN_REGION1_EN_MASK 0x1u
#define AHB_OVERLAY_REGION_1_EN_REGION1_EN_SHIFT 0u
#define AHB_OVERLAY_REGION_1_EN_REGION1_EN_WIDTH 1u
#define AHB_OVERLAY_REGION_1_EN_REGION1_EN(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_REGION_1_EN_REGION1_EN_SHIFT))&AHB_OVERLAY_REGION_1_EN_REGION1_EN_MASK)
/* REGION_1_EN Reg Mask */
#define AHB_OVERLAY_REGION_1_EN_MASK   0x00000001u

/* REGION_2_SRC Bit Fields */
#define AHB_OVERLAY_REGION_2_SRC_REGION2_SRC_MASK 0xFFFFF000u
#define AHB_OVERLAY_REGION_2_SRC_REGION2_SRC_SHIFT 12u
#define AHB_OVERLAY_REGION_2_SRC_REGION2_SRC_WIDTH 20u
#define AHB_OVERLAY_REGION_2_SRC_REGION2_SRC(x) ((uint32_t)(x) & AHB_OVERLAY_REGION_2_SRC_REGION2_SRC_MASK)
/* REGION_2_SRC Reg Mask */
#define AHB_OVERLAY_REGION_2_SRC_MASK  0xFFFFF000u

/* REGION_2_DST Bit Fields */
#define AHB_OVERLAY_REGION_2_DST_REGION2_DST_MASK 0xFFFFF000u
#define AHB_OVERLAY_REGION_2_DST_REGION2_DST_SHIFT 12u
#define AHB_OVERLAY_REGION_2_DST_REGION2_DST_WIDTH 20u
#define AHB_OVERLAY_REGION_2_DST_REGION2_DST(x) ((uint32_t)(x) & AHB_OVERLAY_REGION_2_DST_REGION2_DST_MASK)
/* REGION_2_DST Reg Mask */
#define AHB_OVERLAY_REGION_2_DST_MASK  0xFFFFF000u

/* REGION_2_SIZE Bit Fields */
#define AHB_OVERLAY_REGION_2_SIZE_REGION2_SIZE_MASK 0x1FFu
#define AHB_OVERLAY_REGION_2_SIZE_REGION2_SIZE_SHIFT 0u
#define AHB_OVERLAY_REGION_2_SIZE_REGION2_SIZE_WIDTH 9u
#define AHB_OVERLAY_REGION_2_SIZE_REGION2_SIZE(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_REGION_2_SIZE_REGION2_SIZE_SHIFT))&AHB_OVERLAY_REGION_2_SIZE_REGION2_SIZE_MASK)
/* REGION_2_SIZE Reg Mask */
#define AHB_OVERLAY_REGION_2_SIZE_MASK 0x000001FFu

/* REGION_2_EN Bit Fields */
#define AHB_OVERLAY_REGION_2_EN_REGION2_EN_MASK 0x1u
#define AHB_OVERLAY_REGION_2_EN_REGION2_EN_SHIFT 0u
#define AHB_OVERLAY_REGION_2_EN_REGION2_EN_WIDTH 1u
#define AHB_OVERLAY_REGION_2_EN_REGION2_EN(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_REGION_2_EN_REGION2_EN_SHIFT))&AHB_OVERLAY_REGION_2_EN_REGION2_EN_MASK)
/* REGION_2_EN Reg Mask */
#define AHB_OVERLAY_REGION_2_EN_MASK   0x00000001u

/* GLOBAL_EN Bit Fields */
#define AHB_OVERLAY_GLOBAL_EN_FAR_EN_MASK 0x2u
#define AHB_OVERLAY_GLOBAL_EN_FAR_EN_SHIFT 1u
#define AHB_OVERLAY_GLOBAL_EN_FAR_EN_WIDTH 1u
#define AHB_OVERLAY_GLOBAL_EN_FAR_EN(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_GLOBAL_EN_FAR_EN_SHIFT))&AHB_OVERLAY_GLOBAL_EN_FAR_EN_MASK)
#define AHB_OVERLAY_GLOBAL_EN_OVERLAY_EN_MASK 0x1u
#define AHB_OVERLAY_GLOBAL_EN_OVERLAY_EN_SHIFT 0u
#define AHB_OVERLAY_GLOBAL_EN_OVERLAY_EN_WIDTH 1u
#define AHB_OVERLAY_GLOBAL_EN_OVERLAY_EN(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_GLOBAL_EN_OVERLAY_EN_SHIFT))&AHB_OVERLAY_GLOBAL_EN_OVERLAY_EN_MASK)
/* GLOBAL_EN Reg Mask */
#define AHB_OVERLAY_GLOBAL_EN_MASK     0x00000003u

/* INTR_FLAG Bit Fields */
#define AHB_OVERLAY_INTR_FLAG_REGION2_SIZE_INTR_MASK 0x1000u
#define AHB_OVERLAY_INTR_FLAG_REGION2_SIZE_INTR_SHIFT 12u
#define AHB_OVERLAY_INTR_FLAG_REGION2_SIZE_INTR_WIDTH 1u
#define AHB_OVERLAY_INTR_FLAG_REGION2_SIZE_INTR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_FLAG_REGION2_SIZE_INTR_SHIFT))&AHB_OVERLAY_INTR_FLAG_REGION2_SIZE_INTR_MASK)
#define AHB_OVERLAY_INTR_FLAG_REGION2_DST_INTR_MASK 0x800u
#define AHB_OVERLAY_INTR_FLAG_REGION2_DST_INTR_SHIFT 11u
#define AHB_OVERLAY_INTR_FLAG_REGION2_DST_INTR_WIDTH 1u
#define AHB_OVERLAY_INTR_FLAG_REGION2_DST_INTR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_FLAG_REGION2_DST_INTR_SHIFT))&AHB_OVERLAY_INTR_FLAG_REGION2_DST_INTR_MASK)
#define AHB_OVERLAY_INTR_FLAG_REGION2_SRC_INTR_MASK 0x400u
#define AHB_OVERLAY_INTR_FLAG_REGION2_SRC_INTR_SHIFT 10u
#define AHB_OVERLAY_INTR_FLAG_REGION2_SRC_INTR_WIDTH 1u
#define AHB_OVERLAY_INTR_FLAG_REGION2_SRC_INTR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_FLAG_REGION2_SRC_INTR_SHIFT))&AHB_OVERLAY_INTR_FLAG_REGION2_SRC_INTR_MASK)
#define AHB_OVERLAY_INTR_FLAG_REGION1_SIZE_INTR_MASK 0x80u
#define AHB_OVERLAY_INTR_FLAG_REGION1_SIZE_INTR_SHIFT 7u
#define AHB_OVERLAY_INTR_FLAG_REGION1_SIZE_INTR_WIDTH 1u
#define AHB_OVERLAY_INTR_FLAG_REGION1_SIZE_INTR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_FLAG_REGION1_SIZE_INTR_SHIFT))&AHB_OVERLAY_INTR_FLAG_REGION1_SIZE_INTR_MASK)
#define AHB_OVERLAY_INTR_FLAG_REGION1_DST_INTR_MASK 0x40u
#define AHB_OVERLAY_INTR_FLAG_REGION1_DST_INTR_SHIFT 6u
#define AHB_OVERLAY_INTR_FLAG_REGION1_DST_INTR_WIDTH 1u
#define AHB_OVERLAY_INTR_FLAG_REGION1_DST_INTR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_FLAG_REGION1_DST_INTR_SHIFT))&AHB_OVERLAY_INTR_FLAG_REGION1_DST_INTR_MASK)
#define AHB_OVERLAY_INTR_FLAG_REGION1_SRC_INTR_MASK 0x20u
#define AHB_OVERLAY_INTR_FLAG_REGION1_SRC_INTR_SHIFT 5u
#define AHB_OVERLAY_INTR_FLAG_REGION1_SRC_INTR_WIDTH 1u
#define AHB_OVERLAY_INTR_FLAG_REGION1_SRC_INTR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_FLAG_REGION1_SRC_INTR_SHIFT))&AHB_OVERLAY_INTR_FLAG_REGION1_SRC_INTR_MASK)
#define AHB_OVERLAY_INTR_FLAG_REGION0_SIZE_INTR_MASK 0x4u
#define AHB_OVERLAY_INTR_FLAG_REGION0_SIZE_INTR_SHIFT 2u
#define AHB_OVERLAY_INTR_FLAG_REGION0_SIZE_INTR_WIDTH 1u
#define AHB_OVERLAY_INTR_FLAG_REGION0_SIZE_INTR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_FLAG_REGION0_SIZE_INTR_SHIFT))&AHB_OVERLAY_INTR_FLAG_REGION0_SIZE_INTR_MASK)
#define AHB_OVERLAY_INTR_FLAG_REGION0_DST_INTR_MASK 0x2u
#define AHB_OVERLAY_INTR_FLAG_REGION0_DST_INTR_SHIFT 1u
#define AHB_OVERLAY_INTR_FLAG_REGION0_DST_INTR_WIDTH 1u
#define AHB_OVERLAY_INTR_FLAG_REGION0_DST_INTR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_FLAG_REGION0_DST_INTR_SHIFT))&AHB_OVERLAY_INTR_FLAG_REGION0_DST_INTR_MASK)
#define AHB_OVERLAY_INTR_FLAG_REGION0_SRC_INTR_MASK 0x1u
#define AHB_OVERLAY_INTR_FLAG_REGION0_SRC_INTR_SHIFT 0u
#define AHB_OVERLAY_INTR_FLAG_REGION0_SRC_INTR_WIDTH 1u
#define AHB_OVERLAY_INTR_FLAG_REGION0_SRC_INTR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_FLAG_REGION0_SRC_INTR_SHIFT))&AHB_OVERLAY_INTR_FLAG_REGION0_SRC_INTR_MASK)
/* INTR_FLAG Reg Mask */
#define AHB_OVERLAY_INTR_FLAG_MASK     0x00001CE7u

/* INTR_CLR Bit Fields */
#define AHB_OVERLAY_INTR_CLR_REGION2_SIZE_INTR_CLR_MASK 0x1000u
#define AHB_OVERLAY_INTR_CLR_REGION2_SIZE_INTR_CLR_SHIFT 12u
#define AHB_OVERLAY_INTR_CLR_REGION2_SIZE_INTR_CLR_WIDTH 1u
#define AHB_OVERLAY_INTR_CLR_REGION2_SIZE_INTR_CLR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_CLR_REGION2_SIZE_INTR_CLR_SHIFT))&AHB_OVERLAY_INTR_CLR_REGION2_SIZE_INTR_CLR_MASK)
#define AHB_OVERLAY_INTR_CLR_REGION2_DST_INTR_CLR_MASK 0x800u
#define AHB_OVERLAY_INTR_CLR_REGION2_DST_INTR_CLR_SHIFT 11u
#define AHB_OVERLAY_INTR_CLR_REGION2_DST_INTR_CLR_WIDTH 1u
#define AHB_OVERLAY_INTR_CLR_REGION2_DST_INTR_CLR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_CLR_REGION2_DST_INTR_CLR_SHIFT))&AHB_OVERLAY_INTR_CLR_REGION2_DST_INTR_CLR_MASK)
#define AHB_OVERLAY_INTR_CLR_REGION2_SRC_INTR_CLR_MASK 0x400u
#define AHB_OVERLAY_INTR_CLR_REGION2_SRC_INTR_CLR_SHIFT 10u
#define AHB_OVERLAY_INTR_CLR_REGION2_SRC_INTR_CLR_WIDTH 1u
#define AHB_OVERLAY_INTR_CLR_REGION2_SRC_INTR_CLR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_CLR_REGION2_SRC_INTR_CLR_SHIFT))&AHB_OVERLAY_INTR_CLR_REGION2_SRC_INTR_CLR_MASK)
#define AHB_OVERLAY_INTR_CLR_REGION1_SIZE_INTR_CLR_MASK 0x80u
#define AHB_OVERLAY_INTR_CLR_REGION1_SIZE_INTR_CLR_SHIFT 7u
#define AHB_OVERLAY_INTR_CLR_REGION1_SIZE_INTR_CLR_WIDTH 1u
#define AHB_OVERLAY_INTR_CLR_REGION1_SIZE_INTR_CLR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_CLR_REGION1_SIZE_INTR_CLR_SHIFT))&AHB_OVERLAY_INTR_CLR_REGION1_SIZE_INTR_CLR_MASK)
#define AHB_OVERLAY_INTR_CLR_REGION1_DST_INTR_CLR_MASK 0x40u
#define AHB_OVERLAY_INTR_CLR_REGION1_DST_INTR_CLR_SHIFT 6u
#define AHB_OVERLAY_INTR_CLR_REGION1_DST_INTR_CLR_WIDTH 1u
#define AHB_OVERLAY_INTR_CLR_REGION1_DST_INTR_CLR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_CLR_REGION1_DST_INTR_CLR_SHIFT))&AHB_OVERLAY_INTR_CLR_REGION1_DST_INTR_CLR_MASK)
#define AHB_OVERLAY_INTR_CLR_REGION1_SRC_INTR_CLR_MASK 0x20u
#define AHB_OVERLAY_INTR_CLR_REGION1_SRC_INTR_CLR_SHIFT 5u
#define AHB_OVERLAY_INTR_CLR_REGION1_SRC_INTR_CLR_WIDTH 1u
#define AHB_OVERLAY_INTR_CLR_REGION1_SRC_INTR_CLR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_CLR_REGION1_SRC_INTR_CLR_SHIFT))&AHB_OVERLAY_INTR_CLR_REGION1_SRC_INTR_CLR_MASK)
#define AHB_OVERLAY_INTR_CLR_REGION0_SIZE_INTR_CLR_MASK 0x4u
#define AHB_OVERLAY_INTR_CLR_REGION0_SIZE_INTR_CLR_SHIFT 2u
#define AHB_OVERLAY_INTR_CLR_REGION0_SIZE_INTR_CLR_WIDTH 1u
#define AHB_OVERLAY_INTR_CLR_REGION0_SIZE_INTR_CLR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_CLR_REGION0_SIZE_INTR_CLR_SHIFT))&AHB_OVERLAY_INTR_CLR_REGION0_SIZE_INTR_CLR_MASK)
#define AHB_OVERLAY_INTR_CLR_REGION0_DST_INTR_CLR_MASK 0x2u
#define AHB_OVERLAY_INTR_CLR_REGION0_DST_INTR_CLR_SHIFT 1u
#define AHB_OVERLAY_INTR_CLR_REGION0_DST_INTR_CLR_WIDTH 1u
#define AHB_OVERLAY_INTR_CLR_REGION0_DST_INTR_CLR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_CLR_REGION0_DST_INTR_CLR_SHIFT))&AHB_OVERLAY_INTR_CLR_REGION0_DST_INTR_CLR_MASK)
#define AHB_OVERLAY_INTR_CLR_REGION0_SRC_INTR_CLR_MASK 0x1u
#define AHB_OVERLAY_INTR_CLR_REGION0_SRC_INTR_CLR_SHIFT 0u
#define AHB_OVERLAY_INTR_CLR_REGION0_SRC_INTR_CLR_WIDTH 1u
#define AHB_OVERLAY_INTR_CLR_REGION0_SRC_INTR_CLR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_CLR_REGION0_SRC_INTR_CLR_SHIFT))&AHB_OVERLAY_INTR_CLR_REGION0_SRC_INTR_CLR_MASK)
/* INTR_CLR Reg Mask */
#define AHB_OVERLAY_INTR_CLR_MASK      0x00001CE7u

/* INTR_EN Bit Fields */
#define AHB_OVERLAY_INTR_EN_INTR_ENABLE_MASK 0x1u
#define AHB_OVERLAY_INTR_EN_INTR_ENABLE_SHIFT 0u
#define AHB_OVERLAY_INTR_EN_INTR_ENABLE_WIDTH 1u
#define AHB_OVERLAY_INTR_EN_INTR_ENABLE(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_INTR_EN_INTR_ENABLE_SHIFT))&AHB_OVERLAY_INTR_EN_INTR_ENABLE_MASK)
/* INTR_EN Reg Mask */
#define AHB_OVERLAY_INTR_EN_MASK       0x00000001u

/* FAR_SRC Bit Fields */
#define AHB_OVERLAY_FAR_SRC_FAR_SRC_ADDR_MASK 0xFFFFFFFFu
#define AHB_OVERLAY_FAR_SRC_FAR_SRC_ADDR_SHIFT 0u
#define AHB_OVERLAY_FAR_SRC_FAR_SRC_ADDR_WIDTH 32u
#define AHB_OVERLAY_FAR_SRC_FAR_SRC_ADDR(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_FAR_SRC_FAR_SRC_ADDR_SHIFT))&AHB_OVERLAY_FAR_SRC_FAR_SRC_ADDR_MASK)
/* FAR_SRC Reg Mask */
#define AHB_OVERLAY_FAR_SRC_MASK       0xFFFFFFFFu

/* FAR_DST Bit Fields */
#define AHB_OVERLAY_FAR_DST_FAR_DST_ADDR_MASK 0xFFFF0000u
#define AHB_OVERLAY_FAR_DST_FAR_DST_ADDR_SHIFT 16u
#define AHB_OVERLAY_FAR_DST_FAR_DST_ADDR_WIDTH 16u
#define AHB_OVERLAY_FAR_DST_FAR_DST_ADDR(x) (((uint32_t)(((uint32_t)(x))))&AHB_OVERLAY_FAR_DST_FAR_DST_ADDR_MASK)
/* FAR_DST Reg Mask */
#define AHB_OVERLAY_FAR_DST_MASK       0xFFFF0000u

/* FAR_SIZE Bit Fields */
#define AHB_OVERLAY_FAR_SIZE_FAR_SIZE_VAL_MASK 0x3F0000u
#define AHB_OVERLAY_FAR_SIZE_FAR_SIZE_VAL_SHIFT 16u
#define AHB_OVERLAY_FAR_SIZE_FAR_SIZE_VAL_WIDTH 6u
#define AHB_OVERLAY_FAR_SIZE_FAR_SIZE_VAL(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_FAR_SIZE_FAR_SIZE_VAL_SHIFT))&AHB_OVERLAY_FAR_SIZE_FAR_SIZE_VAL_MASK)
/* FAR_SIZE Reg Mask */
#define AHB_OVERLAY_FAR_SIZE_MASK      0x003F0000u

/* REGION0_MASK Bit Fields */
#define AHB_OVERLAY_REGION0_MASK_REGION0_MASK_MASK 0xFFFFFFFFu
#define AHB_OVERLAY_REGION0_MASK_REGION0_MASK_SHIFT 0u
#define AHB_OVERLAY_REGION0_MASK_REGION0_MASK_WIDTH 32u
#define AHB_OVERLAY_REGION0_MASK_REGION0_MASK(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_REGION0_MASK_REGION0_MASK_SHIFT))&AHB_OVERLAY_REGION0_MASK_REGION0_MASK_MASK)
/* REGION0_MASK Reg Mask */
#define AHB_OVERLAY_REGION0_MASK_MASK  0xFFFFFFFFu

/* REGION1_MASK Bit Fields */
#define AHB_OVERLAY_REGION1_MASK_REGION1_MASK_MASK 0xFFFFFFFFu
#define AHB_OVERLAY_REGION1_MASK_REGION1_MASK_SHIFT 0u
#define AHB_OVERLAY_REGION1_MASK_REGION1_MASK_WIDTH 32u
#define AHB_OVERLAY_REGION1_MASK_REGION1_MASK(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_REGION1_MASK_REGION1_MASK_SHIFT))&AHB_OVERLAY_REGION1_MASK_REGION1_MASK_MASK)
/* REGION1_MASK Reg Mask */
#define AHB_OVERLAY_REGION1_MASK_MASK  0xFFFFFFFFu

/* REGION2_MASK Bit Fields */
#define AHB_OVERLAY_REGION2_MASK_REGION2_MASK_MASK 0xFFFFFFFFu
#define AHB_OVERLAY_REGION2_MASK_REGION2_MASK_SHIFT 0u
#define AHB_OVERLAY_REGION2_MASK_REGION2_MASK_WIDTH 32u
#define AHB_OVERLAY_REGION2_MASK_REGION2_MASK(x) (((uint32_t)(((uint32_t)(x))<<AHB_OVERLAY_REGION2_MASK_REGION2_MASK_SHIFT))&AHB_OVERLAY_REGION2_MASK_REGION2_MASK_MASK)
/* REGION2_MASK Reg Mask */
#define AHB_OVERLAY_REGION2_MASK_MASK  0xFFFFFFFFu


/*!
 * @}
 */ /* end of group AHB_OVERLAY_Register_Masks */

/*!
 * @}
 */ /* end of group AHB_OVERLAY_Peripheral_Access_Layer */

#endif
