#ifndef _DEVICE_FEATURES_FC7300F4MDSxxxxxT1B_TMU_COMMON_H_
#define _DEVICE_FEATURES_FC7300F4MDSxxxxxT1B_TMU_COMMON_H_

#define TMU_SUPPORT_TV_ECMP    (0u)

#endif /* _DEVICE_FEATURES_FC7300F4MDSxxxxxT1B_TMU_COMMON_H_ */
