#ifndef _DEVICE_FEATURES_FC7300F8MDQxxxxxT1B_DMAMUX_COMMON_H_
#define _DEVICE_FEATURES_FC7300F8MDQxxxxxT1B_DMAMUX_COMMON_H_

/************ DMAMUX Features **************/
/** Number of instances of the DMAMUX module. */
#define DMAMUX_INSTANCE_COUNT                    (2u)

/** Array initializer of DMAMUX peripheral base addresses */
#define DMAMUX_BASE_ADDRS                        {DMAMUX0_BASE, DMAMUX1_BASE}
/** Array initializer of DMAMUX peripheral base pointers */
#define DMAMUX_BASE_PTRS                         {DMAMUX0, DMAMUX1}

typedef enum
{
    DMA_REQ_DISABLED                        = 0U,
    DMA_REQ_FCIIC0_RX                       = 1U,
    DMA_REQ_FCIIC0_TX                       = 2U,
    DMA_REQ_FCIIC1_RX                       = 3U,
    DMA_REQ_FCIIC1_TX                       = 4U,
    DMA_REQ_FCSPI0_RX                       = 5U,
    DMA_REQ_FCSPI0_TX                       = 6U,
    DMA_REQ_FCSPI1_RX                       = 7U,
    DMA_REQ_FCSPI1_TX                       = 8U,
    DMA_REQ_FCSPI2_RX                       = 9U,
    DMA_REQ_FCSPI2_TX                       = 10U,
    DMA_REQ_FCSPI3_RX                       = 11U,
    DMA_REQ_FCSPI3_TX                       = 12U,
    DMA_REQ_FCSPI4_RX                       = 13U,
    DMA_REQ_FCSPI4_TX                       = 14U,
    DMA_REQ_FCSPI5_RX                       = 15U,
    DMA_REQ_FCSPI5_TX                       = 16U,
    DMA_REQ_FCSPI6_RX                       = 17U,
    DMA_REQ_FCSPI6_TX                       = 18U,
    DMA_REQ_FCSPI7_RX                       = 19U,
    DMA_REQ_FCSPI7_TX                       = 20U,
    DMA_REQ_EFTU0_SRC1                      = 21U,
    DMA_REQ_EFTU0_SRC2                      = 22U,
    DMA_REQ_FLEXCAN0                        = 23U,
    DMA_REQ_FLEXCAN1                        = 24U,
    DMA_REQ_FLEXCAN2                        = 25U,
    DMA_REQ_FLEXCAN3                        = 26U,
    DMA_REQ_FLEXCAN4                        = 27U,
    DMA_REQ_FLEXCAN5                        = 28U,
    DMA_REQ_FLEXCAN6                        = 29U,
    DMA_REQ_FLEXCAN7                        = 30U,
    DMA_REQ_FLEXCAN8                        = 31U,
    DMA_REQ_FLEXCAN9                        = 32U,
    DMA_REQ_ADC0                            = 33U,
    DMA_REQ_ADC1                            = 34U,
    DMA_REQ_ADC2                            = 35U,
    DMA_REQ_ADC3                            = 36U,
    DMA_REQ_SDADC_CH0                       = 37U,
    DMA_REQ_SDADC_CH1                       = 38U,
    DMA_REQ_SDADC_CH2                       = 39U,
    DMA_REQ_EFTU0_SRC4                      = 40U,
    DMA_REQ_FCUART0_RX                      = 41U,
    DMA_REQ_FCUART0_TX                      = 42U,
    DMA_REQ_FCUART1_RX                      = 43U,
    DMA_REQ_FCUART1_TX                      = 44U,
    DMA_REQ_FCUART2_RX                      = 45U,
    DMA_REQ_FCUART2_TX                      = 46U,
    DMA_REQ_FCUART3_RX                      = 47U,
    DMA_REQ_FCUART3_TX                      = 48U,
    DMA_REQ_FCUART4_RX                      = 49U,
    DMA_REQ_FCUART4_TX                      = 50U,
    DMA_REQ_FCUART5_RX                      = 51U,
    DMA_REQ_FCUART5_TX                      = 52U,
    DMA_REQ_FCUART6_RX                      = 53U,
    DMA_REQ_FCUART6_TX                      = 54U,
    DMA_REQ_FCUART7_RX                      = 55U,
    DMA_REQ_FCUART7_TX                      = 56U,
    DMA_REQ_FCUART8_RX                      = 57U,
    DMA_REQ_FCUART8_TX                      = 58U,
    DMA_REQ_FCUART9_RX                      = 59U,
    DMA_REQ_FCUART9_TX                      = 60U,
    DMA_REQ_FCUART10_RX                     = 61U,
    DMA_REQ_FCUART10_TX                     = 62U,
    DMA_REQ_FCUART11_RX_OR_LU0              = 63U,
    DMA_REQ_FCUART11_TX_OR_LU1              = 64U,
    DMA_REQ_FCUART12_RX_OR_TPU0_CH8_11      = 65U,
    DMA_REQ_FCUART12_TX_OR_TPU0_CH12_15     = 66U,
    DMA_REQ_FCUART13_RX_OR_TPU0_CH16_19     = 67U,
    DMA_REQ_FCUART13_TX_OR_TPU0_CH20_23     = 68U,
    DMA_REQ_ADC4                            = 69U,
    DMA_REQ_ADC5                            = 70U,
    DMA_REQ_HSADC2                          = 71U,
    DMA_REQ_HSADC3                          = 72U,
    DMA_REQ_SDADC1_CH0                      = 73U,
    DMA_REQ_SDADC1_CH1                      = 74U,
    DMA_REQ_SDADC1_CH2                      = 75U,
    DMA_REQ_EFTU0_SRC5                      = 76U,
    DMA_REQ_PORTA_OR_TPU0_CH0_3             = 77U,
    DMA_REQ_PORTB_OR_TPU0_CH4_7             = 78U,
    DMA_REQ_PORTC_OR_EFTU1_SRC1             = 79U,
    DMA_REQ_PORTD_OR_EFTU1_SRC2             = 80U,
    DMA_REQ_PORTE_OR_EFTU1_SRC4             = 81U,
    DMA_REQ_PORTF_OR_EFTU1_SRC5             = 82U,
    DMA_REQ_PORTG_OR_EFTU2_SRC1             = 83U,
    DMA_REQ_PORTH_OR_EFTU2_SRC2             = 84U,
    DMA_REQ_PORTI_OR_EFTU2_SRC4             = 85U,
    DMA_REQ_AONTIMER0_OR_EFTU2_SRC5_OR_TPU0_CH24   = 86U,
    DMA_REQ_CMP0_OR_EFTU0_SRC0_OR_TPU0_CH25        = 87U,
    DMA_REQ_HSADC0                          = 88U,
    DMA_REQ_HSADC1                          = 89U,
    DMA_REQ_PTIMER0_OR_TPU0_CH26_OR_EFTU0_SRC3     = 90U,
    DMA_REQ_PTIMER1_OR_TPU0_CH27_OR_EFTU1_SRC0     = 91U,
    DMA_REQ_PTIMER2_OR_EFTU1_SRC3                  = 92U,
    DMA_REQ_PTIMER3_OR_EFTU2_SRC0                  = 93U,
    DMA_REQ_ENET_PPS_TIMER_CH0              = 94U,
    DMA_REQ_ENET_PPS_TIMER_CH1_OR_EFTU2_SRC3       = 95U,
    DMA_REQ_ENET_PPS_TIMER_CH2_OR_FLASH            = 96U,
    DMA_REQ_ENET_PPS_TIMER_CH3_OR_FLASH            = 97U,
    DMA_REQ_FTU0_ALL_CH_OR                  = 98U,
    DMA_REQ_FTU1_ALL_CH_OR                  = 99U,
    DMA_REQ_FTU2_ALL_CH_OR                  = 100U,
    DMA_REQ_FTU3_ALL_CH_OR                  = 101U,
    DMA_REQ_FTU4_ALL_CH_OR_TPU0_CH28        = 102U,
    DMA_REQ_FTU5_ALL_CH_OR_TPU0_CH29        = 103U,
    DMA_REQ_FTU6_ALL_CH_OR_TPU0_CH30        = 104U,
    DMA_REQ_FTU7_ALL_CH_OR_TPU0_CH31        = 105U,
    DMA_REQ_FTU0_CH0_OR_FLEXCAN10           = 106U,
    DMA_REQ_FTU0_CH2_OR_FLEXCAN11           = 107U,
    DMA_REQ_FTU0_CH4_OR_FLEXCAN12           = 108U,
    DMA_REQ_FTU0_CH6_OR_FLEXCAN13           = 109U,
    DMA_REQ_SENT0_CH0_FAST                  = 110U,
    DMA_REQ_SENT0_CH1_FAST                  = 111U,
    DMA_REQ_SENT0_CH2_FAST                  = 112U,
    DMA_REQ_SENT0_CH3_FAST                  = 113U,
    DMA_REQ_SENT1_CH0_FAST                  = 114U,
    DMA_REQ_SENT1_CH1_FAST                  = 115U,
    DMA_REQ_SENT1_CH2_FAST                  = 116U,
    DMA_REQ_SENT1_CH3_FAST                  = 117U,
    DMA_REQ_SENT0_CH0_SLOW_OR_FTU3_CH0      = 118U,
    DMA_REQ_SENT0_CH1_SLOW_OR_FTU3_CH2      = 119U,
    DMA_REQ_SENT0_CH2_SLOW_OR_FTU3_CH4      = 120U,
    DMA_REQ_SENT0_CH3_SLOW_OR_FTU3_CH6      = 121U,
    DMA_REQ_SENT1_CH0_SLOW_OR_FTU4_CH0      = 122U,
    DMA_REQ_SENT1_CH1_SLOW_OR_FTU4_CH2      = 123U,
    DMA_REQ_SENT1_CH2_SLOW_OR_FTU4_CH4      = 124U,
    DMA_REQ_SENT1_CH3_SLOW_OR_FTU4_CH6      = 125U,
    DMA_REQ_ALWAYS_ENABLE_0                 = 126U,
    DMA_REQ_ALWAYS_ENABLE_1                 = 127U
} DMA_RequestSourceType;

#endif /* _DEVICE_FEATURES_FC7300F8MDQxxxxxT1B_DMAMUX_COMMON_H_ */
