#ifndef _DEVICE_FEATURES_FC7300F8MDQxxxxxT1B_SMC_COMMON_H_
#define _DEVICE_FEATURES_FC7300F8MDQxxxxxT1B_SMC_COMMON_H_


#define SMC_CLOCKCONFIG_SUPPORT         (1u)
#define SMC_TSTMP0CLOCK_CONFIG_SUPPORT  (0u)
#define SMC_LP_GOOD_SUPPORT             (1u)
#define SMC_SCG_WAKEUP_CONFIG_SUPPORT   (1u)
#define SMC_SCG_WAKEUP_SRC_TSTMP_EXT_TRG_SUPPORT    (1u)
#define SMC_SCG_WAKEUP_SRC_TSTMP_EDGE_TRG_SUPPORT   (0u)
#define SMC_CMP0_LPWAKEUP_SUPPORT         (1u)
#define SMC_ADC2_LPWAKEUP_SUPPORT         (1u)
#define SMC_SRAM2_RENTENTION_MODE_SUPPORT (1u)

#define SMC_SCG_WARKEUP_ADC1_AND_ADC2   (1u)

#endif /* _DEVICE_FEATURES_FC7300F8MDQxxxxxT1B_SMC_COMMON_H_ */
