#ifndef _DEVICE_FEATURES_FC7300F8MDQxxxxxT1B_TMU_COMMON_H_
#define _DEVICE_FEATURES_FC7300F8MDQxxxxxT1B_TMU_COMMON_H_

#define TMU_SUPPORT_TRIM
#define TMU_SUPPORT_STOP
#define TMU_SUPPORT_TV_ECMP    (0u)

#endif /* _DEVICE_FEATURES_FC7300F8MDQxxxxxT1B_TMU_COMMON_H_ */
