#ifndef _DEVICE_FEATURES_FC7240_CSC0_COMMON_H_
#define _DEVICE_FEATURES_FC7240_CSC0_COMMON_H_


#define CSC0_CLOCKCONFIG_SUPPORT    (1u)
#define CSC0_SMU_CTRL5_SUPPORT      (1u)

#endif /* _DEVICE_FEATURES_FC7240_CSC0_COMMON_H_ */
