#ifndef _DEVICE_FEATURES_FC7240_OSPI_COMMON_H_
#define _DEVICE_FEATURES_FC7240_OSPI_COMMON_H_

#define OSPI_MODULE_SUPPORT                      (0u)

#endif /* _DEVICE_FEATURES_FC7240_OSPI_COMMON_H_ */
