#ifndef _DEVICE_FEATURES_FC7240F2MDS2_WKU_COMMON_H_
#define _DEVICE_FEATURES_FC7240F2MDS2_WKU_COMMON_H_

/* common features  */
#define WKU_GPIO_TYPE_0_SUPPORT      (0u)
#define WKU_GPIO_TYPE_1_SUPPORT      (1u)
#define WKU_GPIO_TYPE_2_SUPPORT      (0u)
#define WKU_GPIO_TYPE_2_CMP0_SUPPORT (0u)
#define WKU_GPIO_TYPE_2_ADC2_SUPPORT (0u)

#endif /* _DEVICE_FEATURES_FC7240F2MDS2_WKU_COMMON_H_ */
