#ifndef _DEVICE_FEATURES_FLAGCHIP_FLASH_COMMON_H_
#define _DEVICE_FEATURES_FLAGCHIP_FLASH_COMMON_H_

#define FLASH_HARDWARE_STATUS_ADDR       (0x40020000U)
#define FLASH_HARDWARE_STATUS_MASK       (0x00FF0000U)
#define FLASH_HARDWARE_STATUS_IDLE       (0xFFU)

#endif /* _DEVICE_FEATURES_FLAGCHIP_FLASH_COMMON_H_ */
